# Generated by Django 3.2.8 on 2021-10-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_evaluation_matiere_semestre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matiere',
            table=None,
        ),
        migrations.AlterModelTable(
            name='semestre',
            table=None,
        ),
    ]
