# Generated by Django 3.2.8 on 2021-10-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0003_auto_20211029_1300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluation',
            table='evaluation',
        ),
        migrations.AlterModelTable(
            name='matiere',
            table='matiere',
        ),
        migrations.AlterModelTable(
            name='semestre',
            table='semestre',
        ),
    ]
